# Site settings
title: wierd.wtf
email: liminaught@odysseus.bot # Optional
description: >- # Supports newlines
  Come one, come all. See the digital archeology stall.
  Answer the data stream's call, then sink into the digital flood.
baseurl: "" # The subpath of your site, e.g., /blog. Usually empty for root domain.
url: "https://wierd.wtf" # Your site's domain
# twitter_username: your_twitter # Optional
# github_username:  your_github # Optional

# Build settings
markdown: kramdown
theme: null # Using local theme files, not a gem-based theme
plugins:
  - jekyll-feed # Optional, but standard

# Collections Configuration (Crucial for Artifacts)
collections:
  artifacts:
    output: true
    permalink: /artifacts/:path/
defaults:
  - scope:
      path: "" # All files in the project
      type: artifacts
    values:
      layout: artifact

# Sass settings
sass:
  sass_dir: _sass
  style: compressed # Use 'expanded' for easier debugging during development

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
